apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keystone.fullname" . }}-config
  labels:
    {{- include "keystone.labels" . | nindent 4 }}
data:
  ENV_MODE: {{ .Values.backend.env.envMode | quote }}
  SIM_ENABLED: {{ .Values.backend.env.simEnabled | quote }}
  CORS_ORIGINS: {{ .Values.backend.env.corsOrigins | quote }}
  CLASSIFICATION_LEVEL: {{ .Values.classification.level | quote }}
  CLASSIFICATION_BANNER: {{ .Values.classification.bannerText | quote }}
  CLASSIFICATION_COLOR: {{ .Values.classification.color | quote }}
  {{- if not .Values.database.external }}
  DATABASE_HOST: {{ include "keystone.fullname" . }}-db
  {{- else }}
  DATABASE_HOST: {{ .Values.database.host | quote }}
  {{- end }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  {{- if not .Values.redis.external }}
  REDIS_HOST: {{ include "keystone.fullname" . }}-redis
  {{- else }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  {{- end }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
