"""SQLAlchemy models for KEYSTONE."""

from app.models.user import User, Role
from app.models.unit import Unit, Echelon
from app.models.supply import SupplyStatusRecord, SupplyClass, SupplyStatus
from app.models.equipment import (
    EquipmentStatus,
    Equipment,
    EquipmentAssetStatus,
    EquipmentFault,
    FaultSeverity,
    EquipmentDriverAssignment,
)
from app.models.transportation import Movement, MovementStatus
from app.models.convoy_planning import (
    ConvoyPlan,
    ConvoySerial,
    LiftRequest,
    ConvoyPlanStatus,
    RiskAssessmentLevel,
    LiftRequestPriority,
    LiftRequestStatus,
    CargoType,
)
from app.models.maintenance import (
    MaintenanceWorkOrder,
    WorkOrderStatus,
    WorkOrderCategory,
    MaintenancePart,
    PartSource,
    PartStatus,
    MaintenanceLabor,
    LaborType,
    EchelonOfMaintenance,
    MaintenanceLevel,
)
from app.models.maintenance_schedule import (
    PreventiveMaintenanceSchedule,
    MaintenanceDeadline,
    EquipmentRepairOrder,
    PMType,
    DeadlineReason,
    EROStatus,
)
from app.models.report import (
    Report,
    ReportType,
    ReportStatus,
    ReportExportDestination,
    AuthType,
    ReportFormat,
    ReportClassification,
    ScheduleFrequency,
    ReportSection,
    ReportTemplate,
    ReportSchedule,
)
from app.models.raw_data import RawData, SourceType, ParseStatus
from app.models.alert import (
    Alert,
    AlertType,
    AlertSeverity,
    AlertEntityType,
    RuleOperator,
    NotificationChannel,
    AlertRule,
    Notification,
    NotificationPreference,
)
from app.models.canonical_schema import CanonicalField
from app.models.data_template import DataTemplate
from app.models.tak_connection import TAKConnection, ConnectionStatus, TAKProtocol
from app.models.data_source import (
    DataSource,
    DataSourceType,
    DataSourceStatus,
    ProcessedFile,
)
from app.models.system_settings import SystemSetting
from app.models.location import (
    Location,
    EntityType,
    PositionSource,
    SupplyPoint,
    SupplyPointType,
    SupplyPointStatus,
    Route,
    RouteType,
    RouteStatus,
)
from app.models.personnel import (
    Personnel,
    PersonnelStatus,
    PayGrade,
    RifleQualification,
    SwimQualification,
    SecurityClearance,
    DutyStatus,
    Weapon,
    AmmoLoad,
    ConvoyVehicle,
    ConvoyPersonnel,
    ConvoyRole,
)
from app.models.manning import (
    BilletStructure,
    ManningSnapshot,
    Qualification,
)
from app.models.catalog_equipment import EquipmentCatalogItem
from app.models.catalog_supply import SupplyCatalogItem
from app.models.catalog_ammunition import AmmunitionCatalogItem
from app.models.readiness_snapshot import UnitReadinessSnapshot, ReadinessThreshold
from app.models.unit_strength import UnitStrength
from app.models.requisition import (
    Requisition,
    RequisitionLineItem,
    RequisitionApproval,
    RequisitionStatusHistory,
    RequisitionStatus,
    ApprovalAction,
    RequisitionPriority,
    ConditionCode,
)
from app.models.inventory import (
    InventoryRecord,
    InventoryTransaction,
    TransactionType,
)
from app.models.medical import (
    CASEVACPrecedence,
    SecurityAtPickup,
    SpecialEquipmentRequired,
    PatientType,
    MarkingMethod,
    NationalityStatus,
    TriageCategory,
    EvacuationStatus,
    TransportMethod,
    CasualtyReportStatus,
    MedicalTreatmentFacilityType,
    MTFStatus,
    BloodProductType,
    BloodType,
    CasualtyReport,
    CasualtyLog,
    MedicalTreatmentFacility,
    MedicalSupplyBurnRate,
    BloodProduct,
)
from app.models.fuel import (
    FuelFacilityType,
    FuelType,
    FuelStorageStatus,
    FuelTransactionType,
    ConsumptionSource,
    OperationalTempo,
    FuelStoragePoint,
    FuelTransaction,
    FuelConsumptionRate,
    FuelForecast,
)
from app.models.rbac import Permission, CustomRole, role_permissions
from app.models.custody import (
    SensitiveItem,
    SensitiveItemType,
    SecurityClassification,
    ItemConditionCode,
    SensitiveItemStatus,
    TransferType,
    InventoryType,
    InventoryStatus,
    DiscrepancyType,
    AuditAction,
    AuditEntityType,
    CustodyTransfer,
    InventoryEvent,
    InventoryLineItem,
    AuditLog,
)

__all__ = [
    "User",
    "Role",
    "Unit",
    "Echelon",
    "SupplyStatusRecord",
    "SupplyClass",
    "SupplyStatus",
    "EquipmentStatus",
    "Equipment",
    "EquipmentAssetStatus",
    "EquipmentFault",
    "FaultSeverity",
    "EquipmentDriverAssignment",
    "Movement",
    "MovementStatus",
    "MaintenanceWorkOrder",
    "WorkOrderStatus",
    "WorkOrderCategory",
    "MaintenancePart",
    "PartSource",
    "PartStatus",
    "MaintenanceLabor",
    "LaborType",
    "Report",
    "ReportType",
    "ReportStatus",
    "ReportExportDestination",
    "AuthType",
    "ReportFormat",
    "ReportClassification",
    "ScheduleFrequency",
    "ReportSection",
    "ReportTemplate",
    "ReportSchedule",
    "RawData",
    "SourceType",
    "ParseStatus",
    "Alert",
    "AlertType",
    "AlertSeverity",
    "AlertEntityType",
    "RuleOperator",
    "NotificationChannel",
    "AlertRule",
    "Notification",
    "NotificationPreference",
    "CanonicalField",
    "DataTemplate",
    "TAKConnection",
    "ConnectionStatus",
    "TAKProtocol",
    "DataSource",
    "DataSourceType",
    "DataSourceStatus",
    "ProcessedFile",
    "SystemSetting",
    "Location",
    "EntityType",
    "PositionSource",
    "SupplyPoint",
    "SupplyPointType",
    "SupplyPointStatus",
    "Route",
    "RouteType",
    "RouteStatus",
    "Personnel",
    "PersonnelStatus",
    "Weapon",
    "AmmoLoad",
    "ConvoyVehicle",
    "ConvoyPersonnel",
    "ConvoyRole",
    "EquipmentCatalogItem",
    "SupplyCatalogItem",
    "AmmunitionCatalogItem",
    "UnitReadinessSnapshot",
    "ReadinessThreshold",
    "UnitStrength",
    "Requisition",
    "RequisitionLineItem",
    "RequisitionApproval",
    "RequisitionStatusHistory",
    "RequisitionStatus",
    "ApprovalAction",
    "RequisitionPriority",
    "ConditionCode",
    "InventoryRecord",
    "InventoryTransaction",
    "TransactionType",
    "EchelonOfMaintenance",
    "MaintenanceLevel",
    "PreventiveMaintenanceSchedule",
    "MaintenanceDeadline",
    "EquipmentRepairOrder",
    "PMType",
    "DeadlineReason",
    "EROStatus",
    "PayGrade",
    "RifleQualification",
    "SwimQualification",
    "SecurityClearance",
    "DutyStatus",
    "BilletStructure",
    "ManningSnapshot",
    "Qualification",
    "ConvoyPlan",
    "ConvoySerial",
    "LiftRequest",
    "ConvoyPlanStatus",
    "RiskAssessmentLevel",
    "LiftRequestPriority",
    "LiftRequestStatus",
    "CargoType",
    "CASEVACPrecedence",
    "SecurityAtPickup",
    "SpecialEquipmentRequired",
    "PatientType",
    "MarkingMethod",
    "NationalityStatus",
    "TriageCategory",
    "EvacuationStatus",
    "TransportMethod",
    "CasualtyReportStatus",
    "MedicalTreatmentFacilityType",
    "MTFStatus",
    "BloodProductType",
    "BloodType",
    "CasualtyReport",
    "CasualtyLog",
    "MedicalTreatmentFacility",
    "MedicalSupplyBurnRate",
    "BloodProduct",
    "FuelFacilityType",
    "FuelType",
    "FuelStorageStatus",
    "FuelTransactionType",
    "ConsumptionSource",
    "OperationalTempo",
    "FuelStoragePoint",
    "FuelTransaction",
    "FuelConsumptionRate",
    "FuelForecast",
    "SensitiveItem",
    "SensitiveItemType",
    "SecurityClassification",
    "ItemConditionCode",
    "SensitiveItemStatus",
    "TransferType",
    "InventoryType",
    "InventoryStatus",
    "DiscrepancyType",
    "AuditAction",
    "AuditEntityType",
    "CustodyTransfer",
    "InventoryEvent",
    "InventoryLineItem",
    "AuditLog",
    "Permission",
    "CustomRole",
    "role_permissions",
]
