import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useDashboard } from '@/hooks/useDashboard';
import { useAlerts } from '@/hooks/useAlerts';
import SupplyStatusCard from './SupplyStatusCard';
import ReadinessGauge from './ReadinessGauge';
import SustainabilityTimeline from './SustainabilityTimeline';
import ConsumptionChart from './ConsumptionChart';
import AlertBanner from './AlertBanner';
import MiniMapWidget from './MiniMapWidget';
import Card from '@/components/ui/Card';
import { CardSkeleton, TableSkeleton, Skeleton } from '@/components/ui/LoadingSkeleton';
import StatusDot from '@/components/ui/StatusDot';
import {
  SupplyClass,
  SupplyStatus,
  AlertSeverity,
  type SupplyClassSummary,
  type Alert,
} from '@/lib/types';
import { SUPPLY_CLASS_SHORT } from '@/lib/constants';
import { getStatusColor, formatNumber } from '@/lib/utils';

// Route mapping for BFC status tiles
const TILE_ROUTES: Record<string, string> = {
  SUPPLY: '/supply',
  MAINTENANCE: '/maintenance',
  TRANSPORTATION: '/transportation',
  ENGINEERING: '/equipment',
  'HEALTH SVCS': '/medical',
  SERVICES: '/readiness',
};

// Demo data for standalone mode
const demoSupplyData: SupplyClassSummary[] = [
  { supplyClass: SupplyClass.I, name: 'Subsistence', percentage: 85, dos: 8, status: SupplyStatus.GREEN, trend: 'STABLE', onHand: 8500, authorized: 10000 },
  { supplyClass: SupplyClass.III, name: 'POL', percentage: 62, dos: 4, status: SupplyStatus.AMBER, trend: 'DOWN', onHand: 6200, authorized: 10000 },
  { supplyClass: SupplyClass.V, name: 'Ammunition', percentage: 45, dos: 2, status: SupplyStatus.RED, trend: 'DOWN', onHand: 4500, authorized: 10000 },
  { supplyClass: SupplyClass.VIII, name: 'Medical', percentage: 92, dos: 14, status: SupplyStatus.GREEN, trend: 'UP', onHand: 9200, authorized: 10000 },
  { supplyClass: SupplyClass.IX, name: 'Repair Parts', percentage: 71, dos: 5, status: SupplyStatus.AMBER, trend: 'STABLE', onHand: 7100, authorized: 10000 },
  { supplyClass: SupplyClass.II, name: 'Clothing & Equip', percentage: 88, dos: 10, status: SupplyStatus.GREEN, trend: 'UP', onHand: 8800, authorized: 10000 },
];

const demoAlerts: Alert[] = [
  { id: '1', type: 'SUPPLY_CRITICAL' as never, severity: AlertSeverity.CRITICAL, unitId: '1-1', unitName: '1/1 BN', title: 'CL V CRITICAL', message: 'Ammunition below 50% - 2 DOS remaining', acknowledged: false, resolved: false, escalated: false, autoGenerated: true, createdAt: new Date(Date.now() - 1800000).toISOString() },
  { id: '2', type: 'SUPPLY_LOW' as never, severity: AlertSeverity.WARNING, unitId: '2-1', unitName: '2/1 BN', title: 'CL III LOW', message: 'POL at 62% authorized level - consumption rate increasing', acknowledged: false, resolved: false, escalated: false, autoGenerated: true, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: '3', type: 'EQUIPMENT_DOWN' as never, severity: AlertSeverity.WARNING, unitId: '1-1', unitName: '1/1 BN', title: 'AAV READINESS DROP', message: '3x AAV NMC - parts on order, ETA 48hrs', acknowledged: false, resolved: false, escalated: false, autoGenerated: true, createdAt: new Date(Date.now() - 7200000).toISOString() },
];

export default function CommanderView() {
  const navigate = useNavigate();
  const [hoveredTile, setHoveredTile] = useState<string | null>(null);
  const { summary, supplyOverview, readiness, sustainability, isLoading } = useDashboard();
  const { alerts, acknowledgeAlert } = useAlerts();

  const supplyData = supplyOverview || demoSupplyData;
  const displayAlerts = alerts.length > 0 ? alerts : demoAlerts;

  // Derive readiness data from API or use summary-based data
  const readinessData = useMemo(() => {
    if (readiness?.byType && readiness.byType.length > 0) {
      return readiness.byType.map((r) => ({
        type: r.type,
        percent: r.readinessPercent,
      }));
    }
    return [];
  }, [readiness]);

  // Compute status tiles from API data when available
  const statusTiles = useMemo(() => {
    const supplyPct = supplyOverview
      ? Math.round(supplyOverview.reduce((s, c) => s + c.percentage, 0) / supplyOverview.length)
      : 74;
    const supplyGreenCount = supplyOverview
      ? supplyOverview.filter((c) => c.status === SupplyStatus.GREEN).length
      : 6;
    const supplyTotal = supplyOverview ? supplyOverview.length : 10;

    const maintenancePct = readiness?.overall ?? 84;
    const maintenanceStatus = maintenancePct >= 90 ? SupplyStatus.GREEN : maintenancePct >= 75 ? SupplyStatus.AMBER : SupplyStatus.RED;

    const movementCount = summary?.activeMovements ?? 3;

    return [
      { label: 'SUPPLY', status: supplyPct >= 80 ? SupplyStatus.GREEN : supplyPct >= 60 ? SupplyStatus.AMBER : SupplyStatus.RED, value: supplyPct, detail: `${supplyGreenCount}/${supplyTotal} classes green` },
      { label: 'MAINTENANCE', status: maintenanceStatus, value: Math.round(maintenancePct), detail: readiness ? `${readiness.byType.reduce((s, r) => s + r.missionCapable, 0)}/${readiness.byType.reduce((s, r) => s + r.authorized, 0)} MC` : '312/371 MC' },
      { label: 'TRANSPORTATION', status: SupplyStatus.GREEN, value: 91, detail: `${movementCount} active convoys` },
      { label: 'ENGINEERING', status: SupplyStatus.GREEN, value: 95, detail: 'All projects on track' },
      { label: 'HEALTH SVCS', status: SupplyStatus.GREEN, value: 92, detail: 'CL VIII adequate' },
      { label: 'SERVICES', status: SupplyStatus.AMBER, value: 78, detail: '2 facilities degraded' },
    ];
  }, [supplyOverview, readiness, summary]);

  if (isLoading) {
    return (
      <div className="flex flex-col gap-4">
        {/* BFC status cards row */}
        <div className="grid-responsive-6col">
          {Array.from({ length: 6 }).map((_, i) => (
            <CardSkeleton key={i} />
          ))}
        </div>
        {/* Supply class status + Equipment readiness */}
        <div className="grid-responsive-2fr1fr">
          <TableSkeleton rows={4} />
          <Skeleton variant="chart" />
        </div>
        {/* Sustainability + Consumption charts */}
        <div className="grid-responsive-2col">
          <Skeleton variant="chart" />
          <Skeleton variant="chart" />
        </div>
        {/* Active alerts */}
        <Skeleton variant="table" />
      </div>
    );
  }

  return (
    <div className="animate-fade-in flex flex-col gap-4">
      {/* Top Row: Status Tiles */}
      <div className="grid-responsive-6col">
        {statusTiles.map((tile) => {
          const color = getStatusColor(tile.status);
          const route = TILE_ROUTES[tile.label];
          const isHovered = hoveredTile === tile.label;
          return (
            <div
              key={tile.label}
              role="button"
              tabIndex={0}
              className="bg-[var(--color-bg-elevated)] border border-[var(--color-border)] rounded-[var(--radius)] py-3 px-3.5 cursor-pointer relative"
              style={{
                borderTop: `2px solid ${color}`,
                borderColor: isHovered ? 'var(--color-border-strong)' : undefined,
                transition: 'background-color var(--transition), border-color var(--transition)',
              }}
              onClick={() => route && navigate(route)}
              onKeyDown={(e) => {
                if ((e.key === 'Enter' || e.key === ' ') && route) navigate(route);
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.backgroundColor = 'var(--color-bg-hover)';
                setHoveredTile(tile.label);
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.backgroundColor = 'var(--color-bg-elevated)';
                setHoveredTile(null);
              }}
            >
              <div
                className="flex items-center justify-between mb-1.5"
              >
                <span className="section-header">{tile.label}</span>
                <StatusDot status={tile.status} pulse={tile.status === SupplyStatus.RED} />
              </div>
              <div
                className="font-[var(--font-mono)] text-[32px] font-bold leading-none mb-1" style={{ color: color }}
              >
                {tile.value}%
              </div>
              <div className="flex items-center justify-between">
                <div
                  className="font-[var(--font-mono)] text-[9px] text-[var(--color-text-muted)] tracking-[0.5px]"
                >
                  {tile.detail}
                </div>
                <span
                  className="font-[var(--font-mono)] text-[9px] text-[var(--color-accent)] tracking-[0.5px]"
                  style={{
                    opacity: isHovered ? 1 : 0,
                    transition: 'opacity var(--transition)',
                  }}
                >
                  View →
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Middle Row: Supply Cards + Readiness */}
      <div className="grid-responsive-2fr1fr">
        {/* Supply Status Cards */}
        <Card title="SUPPLY CLASS STATUS">
          <div className="grid-responsive-3col gap-2.5" >
            {supplyData.map((s) => (
              <SupplyStatusCard key={s.supplyClass} data={s} />
            ))}
          </div>
        </Card>

        {/* Equipment Readiness */}
        <Card title="EQUIPMENT READINESS">
          <div
            className="grid-responsive-3col"
            style={{
              justifyItems: 'center',
            }}
          >
            {readinessData.map((eq) => (
              <ReadinessGauge key={eq.type} percent={eq.percent} label={eq.type} size={72} />
            ))}
          </div>
        </Card>
      </div>

      {/* Sustainability + Consumption */}
      <div className="grid-responsive-2col">
        <SustainabilityTimeline data={sustainability ?? undefined} />
        <ConsumptionChart />
      </div>

      {/* Operational Map + Active Alerts */}
      <div className="grid-responsive-2fr1fr">
        {/* Active Alerts */}
        <Card title="ACTIVE ALERTS" accentColor="var(--color-warning)">
        <AlertBanner
          alerts={displayAlerts}
          onAcknowledge={acknowledgeAlert}
        />
      </Card>

        {/* Mini Map */}
        <MiniMapWidget />
      </div>
    </div>
  );
}
