import { useMemo } from 'react';
import { useDashboard } from '@/hooks/useDashboard';
import { useAlerts } from '@/hooks/useAlerts';
import Card from '@/components/ui/Card';
import StatusDot from '@/components/ui/StatusDot';
import AlertBanner from './AlertBanner';
import {
  SupplyStatus,
  AlertSeverity,
  type Alert,
} from '@/lib/types';
import { getStatusColor } from '@/lib/utils';
import { CardSkeleton } from '@/components/ui/LoadingSkeleton';

const demoAlerts: Alert[] = [
  { id: '1', type: 'SUPPLY_CRITICAL' as never, severity: AlertSeverity.CRITICAL, unitId: '1-1', unitName: '1/1 BN', title: 'CL V CRITICAL', message: 'Ammunition below 50% - 2 DOS remaining', acknowledged: false, resolved: false, escalated: false, autoGenerated: true, createdAt: new Date(Date.now() - 1800000).toISOString() },
  { id: '2', type: 'SUPPLY_LOW' as never, severity: AlertSeverity.WARNING, unitId: '2-1', unitName: '2/1 BN', title: 'CL III LOW', message: 'POL at 62% authorized level - consumption rate increasing', acknowledged: false, resolved: false, escalated: false, autoGenerated: true, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: '3', type: 'EQUIPMENT_DOWN' as never, severity: AlertSeverity.WARNING, unitId: '1-1', unitName: '1/1 BN', title: 'AAV READINESS DROP', message: '3x AAV NMC - parts on order, ETA 48hrs', acknowledged: false, resolved: false, escalated: false, autoGenerated: true, createdAt: new Date(Date.now() - 7200000).toISOString() },
];

export default function ViewerDashboard() {
  const { summary, supplyOverview, readiness, isLoading } = useDashboard();
  const { alerts } = useAlerts();

  const displayAlerts = alerts.length > 0 ? alerts : demoAlerts;

  const statusTiles = useMemo(() => {
    const supplyPct = supplyOverview
      ? Math.round(supplyOverview.reduce((s, c) => s + c.percentage, 0) / supplyOverview.length)
      : 74;
    const supplyGreenCount = supplyOverview
      ? supplyOverview.filter((c) => c.status === SupplyStatus.GREEN).length
      : 6;
    const supplyTotal = supplyOverview ? supplyOverview.length : 10;

    const maintenancePct = readiness?.overall ?? 84;
    const maintenanceStatus = maintenancePct >= 90 ? SupplyStatus.GREEN : maintenancePct >= 75 ? SupplyStatus.AMBER : SupplyStatus.RED;

    const movementCount = summary?.activeMovements ?? 3;

    return [
      { label: 'SUPPLY', status: supplyPct >= 80 ? SupplyStatus.GREEN : supplyPct >= 60 ? SupplyStatus.AMBER : SupplyStatus.RED, value: supplyPct, detail: `${supplyGreenCount}/${supplyTotal} classes green` },
      { label: 'MAINTENANCE', status: maintenanceStatus, value: Math.round(maintenancePct), detail: readiness ? `${readiness.byType.reduce((s, r) => s + r.missionCapable, 0)}/${readiness.byType.reduce((s, r) => s + r.authorized, 0)} MC` : '312/371 MC' },
      { label: 'TRANSPORTATION', status: SupplyStatus.GREEN, value: 91, detail: `${movementCount} active convoys` },
      { label: 'ENGINEERING', status: SupplyStatus.GREEN, value: 95, detail: 'All projects on track' },
      { label: 'HEALTH SVCS', status: SupplyStatus.GREEN, value: 92, detail: 'CL VIII adequate' },
      { label: 'SERVICES', status: SupplyStatus.AMBER, value: 78, detail: '2 facilities degraded' },
    ];
  }, [supplyOverview, readiness, summary]);

  if (isLoading) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
        <div className="grid-responsive-6col">
          {Array.from({ length: 6 }).map((_, i) => (
            <CardSkeleton key={i} />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      {/* Read-Only Status Overview */}
      <div
        style={{
          fontFamily: 'var(--font-mono)',
          fontSize: 9,
          letterSpacing: '1.5px',
          color: 'var(--color-text-muted)',
          textTransform: 'uppercase',
          marginBottom: -8,
        }}
      >
        READ-ONLY VIEW
      </div>

      {/* Status Tiles */}
      <div className="grid-responsive-6col">
        {statusTiles.map((tile) => {
          const color = getStatusColor(tile.status);
          return (
            <div
              key={tile.label}
              style={{
                backgroundColor: 'var(--color-bg-elevated)',
                border: '1px solid var(--color-border)',
                borderTop: `2px solid ${color}`,
                borderRadius: 'var(--radius)',
                padding: '12px 14px',
              }}
            >
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  marginBottom: 6,
                }}
              >
                <span className="section-header">{tile.label}</span>
                <StatusDot status={tile.status} pulse={tile.status === SupplyStatus.RED} />
              </div>
              <div
                style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: 32,
                  fontWeight: 700,
                  color: color,
                  lineHeight: 1,
                  marginBottom: 4,
                }}
              >
                {tile.value}%
              </div>
              <div
                style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: 9,
                  color: 'var(--color-text-muted)',
                  letterSpacing: '0.5px',
                }}
              >
                {tile.detail}
              </div>
            </div>
          );
        })}
      </div>

      {/* Active Alerts (read-only, no acknowledge button) */}
      <Card title="ACTIVE ALERTS" accentColor="var(--color-warning)">
        <AlertBanner alerts={displayAlerts} />
      </Card>
    </div>
  );
}
