"""Seed the equipment catalog with ~110 USMC equipment items.

Covers tactical vehicles, combat vehicles, artillery, infantry weapons,
communications, optics/NVG, aviation, watercraft, generators, CBRN,
EW, shelters, water/fuel systems, engineer equipment, and field services.

Idempotent — checks TAMCN before inserting.
"""

import logging
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.catalog_equipment import EquipmentCatalogItem

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Seed data — all items use supply_class="VII" and is_serialized=True
# unless overridden below.
# ---------------------------------------------------------------------------

_EQUIPMENT_CATALOG: list[dict] = [
    # -----------------------------------------------------------------------
    # TACTICAL VEHICLES (~24 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "E0846",
        "nsn": "2320-01-669-2322",
        "nomenclature": "JLTV M1280A1, Utility",
        "common_name": "Joint Light Tactical Vehicle (JLTV) - Utility",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 14000,
        "crew_size": 2,
        "pax_capacity": 4,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0847",
        "nsn": "2320-01-669-2323",
        "nomenclature": "JLTV M1280A1, General Purpose",
        "common_name": "JLTV - GP",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 15000,
        "crew_size": 2,
        "pax_capacity": 4,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0848",
        "nsn": "2320-01-669-2324",
        "nomenclature": "JLTV M1280A1, Close Combat Weapons Carrier",
        "common_name": "JLTV - CCWC",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 16500,
        "crew_size": 2,
        "pax_capacity": 3,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0849",
        "nsn": "2320-01-669-2325",
        "nomenclature": "JLTV M1280A1, Heavy Guns Carrier",
        "common_name": "JLTV - HGC",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 18000,
        "crew_size": 3,
        "pax_capacity": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0850",
        "nsn": "2320-01-669-2326",
        "nomenclature": "JLTV M1281A1, 2-Seat Companion Trailer",
        "common_name": "JLTV Trailer",
        "category": "Trailer",
        "subcategory": "Light Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 5000,
        "crew_size": 0,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "D1195",
        "nsn": "2320-01-346-9317",
        "nomenclature": "HMMWV M1151A1, Up-Armored",
        "common_name": "Humvee - Up-Armored",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "AM General",
        "weight_lbs": 12100,
        "crew_size": 2,
        "pax_capacity": 4,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "D1191",
        "nsn": "2320-01-097-2145",
        "nomenclature": "HMMWV M998A2, Cargo/Troop Carrier",
        "common_name": "Humvee - Cargo",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "AM General",
        "weight_lbs": 8600,
        "crew_size": 1,
        "pax_capacity": 3,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "D1193",
        "nsn": "2320-01-412-0143",
        "nomenclature": "HMMWV M1114, Up-Armored Armament Carrier",
        "common_name": "Humvee - UAH",
        "category": "Tactical Vehicle",
        "subcategory": "Light Tactical",
        "manufacturer": "AM General",
        "weight_lbs": 12900,
        "crew_size": 2,
        "pax_capacity": 4,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "D1196",
        "nsn": "2310-01-350-3191",
        "nomenclature": "HMMWV M997A2, Ambulance",
        "common_name": "Humvee - Ambulance",
        "category": "Tactical Vehicle",
        "subcategory": "Ambulance",
        "manufacturer": "AM General",
        "weight_lbs": 9800,
        "crew_size": 2,
        "pax_capacity": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1234",
        "nsn": "2320-01-454-3385",
        "nomenclature": "MTVR MK23, Standard Cargo",
        "common_name": "7-ton Truck",
        "category": "Tactical Vehicle",
        "subcategory": "Medium Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 30000,
        "crew_size": 2,
        "pax_capacity": 16,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1235",
        "nsn": "2320-01-454-3386",
        "nomenclature": "MTVR MK25, Standard Cargo w/Winch",
        "common_name": "7-ton Truck w/Winch",
        "category": "Tactical Vehicle",
        "subcategory": "Medium Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 30800,
        "crew_size": 2,
        "pax_capacity": 16,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1236",
        "nsn": "2320-01-454-3387",
        "nomenclature": "MTVR MK27, Extended Cargo",
        "common_name": "7-ton Extended Bed",
        "category": "Tactical Vehicle",
        "subcategory": "Medium Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 31000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1238",
        "nsn": "2320-01-454-3389",
        "nomenclature": "MTVR MK29, Dump Truck",
        "common_name": "7-ton Dump",
        "category": "Tactical Vehicle",
        "subcategory": "Medium Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 33000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1240",
        "nsn": "2320-01-454-3391",
        "nomenclature": "MTVR MK31, Tractor",
        "common_name": "7-ton Tractor",
        "category": "Tactical Vehicle",
        "subcategory": "Medium Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 28000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1244",
        "nsn": "2320-01-454-3395",
        "nomenclature": "MTVR MK36, Wrecker",
        "common_name": "7-ton Wrecker",
        "category": "Tactical Vehicle",
        "subcategory": "Recovery",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 48000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1246",
        "nsn": "2320-01-521-4312",
        "nomenclature": "MTVR MK37, HIMARS Resupply Vehicle",
        "common_name": "HIMARS Resupply",
        "category": "Tactical Vehicle",
        "subcategory": "Medium Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 31500,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1266",
        "nsn": "2320-01-153-1584",
        "nomenclature": "LVS MK48/18, Tractor",
        "common_name": "LVS Power Unit",
        "category": "Tactical Vehicle",
        "subcategory": "Heavy Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 52000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D1267",
        "nsn": "2320-01-153-1585",
        "nomenclature": "LVS MK48/15, Cargo Module",
        "common_name": "LVS Cargo",
        "category": "Tactical Vehicle",
        "subcategory": "Heavy Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 54000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E0880",
        "nsn": "2320-01-575-0890",
        "nomenclature": "LVSR MKR18, Cargo",
        "common_name": "LVSR Cargo",
        "category": "Tactical Vehicle",
        "subcategory": "Heavy Tactical",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 63500,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E0881",
        "nsn": "2320-01-575-0891",
        "nomenclature": "LVSR MKR16, Wrecker",
        "common_name": "LVSR Wrecker",
        "category": "Tactical Vehicle",
        "subcategory": "Recovery",
        "manufacturer": "Oshkosh Defense",
        "weight_lbs": 67000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E0900",
        "nsn": "2320-01-598-4512",
        "nomenclature": "M1161 Growler ITV",
        "common_name": "Growler Internal Transport Vehicle",
        "category": "Tactical Vehicle",
        "subcategory": "Utility",
        "manufacturer": "General Dynamics",
        "weight_lbs": 4000,
        "crew_size": 2,
        "pax_capacity": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0902",
        "nsn": "2320-01-612-3345",
        "nomenclature": "MRZR-4 LT-ATV",
        "common_name": "Polaris MRZR Ultra-Light Tactical Vehicle",
        "category": "Tactical Vehicle",
        "subcategory": "Ultra-Light",
        "manufacturer": "Polaris Defense",
        "weight_lbs": 2200,
        "crew_size": 2,
        "pax_capacity": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0870",
        "nsn": "3930-01-523-4561",
        "nomenclature": "TRAM MK4, Forklift 6000lb",
        "common_name": "TRAM Rough Terrain Forklift",
        "category": "Material Handling",
        "subcategory": "Forklift",
        "manufacturer": "CAT",
        "weight_lbs": 16000,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E0871",
        "nsn": "3930-01-523-4562",
        "nomenclature": "Forklift, 10K lb, Rough Terrain",
        "common_name": "10K Forklift",
        "category": "Material Handling",
        "subcategory": "Forklift",
        "manufacturer": "CAT",
        "weight_lbs": 28000,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    # -----------------------------------------------------------------------
    # COMBAT VEHICLES (~18 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "E0950",
        "nsn": "2350-01-687-1234",
        "nomenclature": "ACV-P, Amphibious Combat Vehicle - Personnel",
        "common_name": "ACV Personnel Variant",
        "category": "Combat Vehicle",
        "subcategory": "Amphibious",
        "manufacturer": "BAE Systems / IVECO",
        "weight_lbs": 70000,
        "crew_size": 3,
        "pax_capacity": 13,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0951",
        "nsn": "2350-01-687-1235",
        "nomenclature": "ACV-30, Amphibious Combat Vehicle - 30mm",
        "common_name": "ACV Gun Variant",
        "category": "Combat Vehicle",
        "subcategory": "Amphibious",
        "manufacturer": "BAE Systems / IVECO",
        "weight_lbs": 72000,
        "crew_size": 3,
        "pax_capacity": 6,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E0952",
        "nsn": "2350-01-687-1236",
        "nomenclature": "ACV-C, Amphibious Combat Vehicle - Command",
        "common_name": "ACV Command Variant",
        "category": "Combat Vehicle",
        "subcategory": "Amphibious",
        "manufacturer": "BAE Systems / IVECO",
        "weight_lbs": 71000,
        "crew_size": 3,
        "pax_capacity": 8,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E0953",
        "nsn": "2350-01-687-1237",
        "nomenclature": "ACV-R, Amphibious Combat Vehicle - Recovery",
        "common_name": "ACV Recovery Variant",
        "category": "Combat Vehicle",
        "subcategory": "Recovery",
        "manufacturer": "BAE Systems / IVECO",
        "weight_lbs": 74000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B0155",
        "nsn": "2350-01-126-8215",
        "nomenclature": "AAV-P7A1, Assault Amphibian Vehicle - Personnel",
        "common_name": "Amtrac",
        "category": "Combat Vehicle",
        "subcategory": "Amphibious",
        "manufacturer": "BAE Systems / FMC",
        "weight_lbs": 60000,
        "crew_size": 3,
        "pax_capacity": 21,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "B0157",
        "nsn": "2350-01-126-8217",
        "nomenclature": "AAV-C7A1, Assault Amphibian Vehicle - Command",
        "common_name": "Amtrac Command",
        "category": "Combat Vehicle",
        "subcategory": "Amphibious",
        "manufacturer": "BAE Systems / FMC",
        "weight_lbs": 58000,
        "crew_size": 3,
        "pax_capacity": 5,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B0158",
        "nsn": "2350-01-126-8218",
        "nomenclature": "AAV-R7A1, Assault Amphibian Vehicle - Recovery",
        "common_name": "Amtrac Recovery",
        "category": "Combat Vehicle",
        "subcategory": "Recovery",
        "manufacturer": "BAE Systems / FMC",
        "weight_lbs": 64000,
        "crew_size": 5,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B0163",
        "nsn": "2350-01-143-0345",
        "nomenclature": "LAV-25A2, Light Armored Vehicle",
        "common_name": "LAV-25",
        "category": "Combat Vehicle",
        "subcategory": "Light Armored",
        "manufacturer": "GDLS Canada",
        "weight_lbs": 28400,
        "crew_size": 3,
        "pax_capacity": 6,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "B0164",
        "nsn": "2350-01-143-0346",
        "nomenclature": "LAV-AT, Anti-Tank",
        "common_name": "LAV Anti-Tank (TOW)",
        "category": "Combat Vehicle",
        "subcategory": "Light Armored",
        "manufacturer": "GDLS Canada",
        "weight_lbs": 27000,
        "crew_size": 4,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "B0165",
        "nsn": "2350-01-143-0347",
        "nomenclature": "LAV-M, Mortar Carrier",
        "common_name": "LAV Mortar",
        "category": "Combat Vehicle",
        "subcategory": "Light Armored",
        "manufacturer": "GDLS Canada",
        "weight_lbs": 26500,
        "crew_size": 5,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "B0166",
        "nsn": "2350-01-143-0348",
        "nomenclature": "LAV-C2, Command & Control",
        "common_name": "LAV Command",
        "category": "Combat Vehicle",
        "subcategory": "Light Armored",
        "manufacturer": "GDLS Canada",
        "weight_lbs": 27000,
        "crew_size": 6,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B0167",
        "nsn": "2350-01-143-0349",
        "nomenclature": "LAV-L, Logistics",
        "common_name": "LAV Logistics",
        "category": "Combat Vehicle",
        "subcategory": "Light Armored",
        "manufacturer": "GDLS Canada",
        "weight_lbs": 25000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B0168",
        "nsn": "2350-01-143-0350",
        "nomenclature": "LAV-R, Recovery",
        "common_name": "LAV Recovery",
        "category": "Combat Vehicle",
        "subcategory": "Light Armored",
        "manufacturer": "GDLS Canada",
        "weight_lbs": 28000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B2200",
        "nsn": "2350-01-547-1989",
        "nomenclature": "M88A2 HERCULES, Armored Recovery Vehicle",
        "common_name": "M88 Recovery Vehicle",
        "category": "Combat Vehicle",
        "subcategory": "Recovery",
        "manufacturer": "BAE Systems",
        "weight_lbs": 140000,
        "crew_size": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B3100",
        "nsn": "2350-01-309-8912",
        "nomenclature": "M1 ABV, Assault Breacher Vehicle",
        "common_name": "Assault Breacher",
        "category": "Combat Vehicle",
        "subcategory": "Engineer",
        "manufacturer": "BAE Systems",
        "weight_lbs": 150000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B3101",
        "nsn": "2350-01-456-7890",
        "nomenclature": "M9 ACE, Armored Combat Earthmover",
        "common_name": "Combat Bulldozer",
        "category": "Combat Vehicle",
        "subcategory": "Engineer",
        "manufacturer": "BAE Systems",
        "weight_lbs": 37000,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "B3110",
        "nsn": "5420-01-100-1234",
        "nomenclature": "M60 AVLB, Armored Vehicle Launched Bridge",
        "common_name": "Bridge Layer",
        "category": "Combat Vehicle",
        "subcategory": "Engineer",
        "manufacturer": "GDLS",
        "weight_lbs": 123000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "F0001",
        "nsn": "1440-01-700-0001",
        "nomenclature": "NMESIS, Navy-Marine Expeditionary Ship Interdiction System",
        "common_name": "NMESIS Anti-Ship Launcher",
        "category": "Weapons System",
        "subcategory": "Anti-Ship",
        "manufacturer": "Raytheon / Kongsberg",
        "weight_lbs": 5000,
        "crew_size": 2,
        "echelon_typical": "BN",
        "notes": "Unmanned JLTV-based NSM launcher for Marine Littoral Regiments",
    },
    # -----------------------------------------------------------------------
    # ARTILLERY SYSTEMS (3 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "D0850",
        "nsn": "1025-01-456-3210",
        "nomenclature": "M777A2, Lightweight 155mm Howitzer",
        "common_name": "M777 Howitzer",
        "category": "Artillery",
        "subcategory": "Towed",
        "manufacturer": "BAE Systems",
        "weight_lbs": 9300,
        "crew_size": 8,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E0830",
        "nsn": "1055-01-521-7891",
        "nomenclature": "M142 HIMARS, High Mobility Artillery Rocket System",
        "common_name": "HIMARS",
        "category": "Artillery",
        "subcategory": "Rocket",
        "manufacturer": "Lockheed Martin",
        "weight_lbs": 35000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "D0860",
        "nsn": "1015-01-234-5678",
        "nomenclature": "M327 EFSS, Expeditionary Fire Support System 120mm Mortar",
        "common_name": "120mm EFSS Mortar",
        "category": "Artillery",
        "subcategory": "Mortar",
        "manufacturer": "Soltam / General Dynamics",
        "weight_lbs": 3500,
        "crew_size": 5,
        "echelon_typical": "BN",
    },
    # -----------------------------------------------------------------------
    # INFANTRY WEAPONS (21 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "A0100",
        "nsn": "1005-01-591-5825",
        "nomenclature": "M27 IAR, Infantry Automatic Rifle 5.56mm",
        "common_name": "M27 IAR (HK416)",
        "category": "Infantry Weapon",
        "subcategory": "Rifle",
        "manufacturer": "Heckler & Koch",
        "weight_lbs": 9,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0101",
        "nsn": "1005-01-383-2872",
        "nomenclature": "M4A1 Carbine, 5.56mm",
        "common_name": "M4 Carbine",
        "category": "Infantry Weapon",
        "subcategory": "Rifle",
        "manufacturer": "Colt / FN",
        "weight_lbs": 7,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0110",
        "nsn": "1005-01-653-4710",
        "nomenclature": "M38 SDMR, Squad Designated Marksman Rifle 5.56mm",
        "common_name": "M38 Designated Marksman Rifle",
        "category": "Infantry Weapon",
        "subcategory": "Rifle",
        "manufacturer": "Heckler & Koch",
        "weight_lbs": 11,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0120",
        "nsn": "1005-01-373-8703",
        "nomenclature": "M40A6 Sniper Rifle, 7.62mm",
        "common_name": "M40 Sniper Rifle",
        "category": "Infantry Weapon",
        "subcategory": "Sniper",
        "manufacturer": "Remington / USMC Armorers",
        "weight_lbs": 16,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "A0121",
        "nsn": "1005-01-592-4781",
        "nomenclature": "Mk13 Mod 7 Sniper Rifle, .300 Win Mag",
        "common_name": "Mk13 Sniper Rifle",
        "category": "Infantry Weapon",
        "subcategory": "Sniper",
        "manufacturer": "Remington",
        "weight_lbs": 18,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "A0125",
        "nsn": "1005-01-527-9101",
        "nomenclature": "M107 SASR, .50 Cal Semi-Auto Sniper Rifle",
        "common_name": "Barrett .50 Cal",
        "category": "Infantry Weapon",
        "subcategory": "Sniper",
        "manufacturer": "Barrett",
        "weight_lbs": 31,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "A0150",
        "nsn": "1005-01-128-9936",
        "nomenclature": "M2A1 HB Machine Gun, .50 Cal",
        "common_name": "Ma Deuce .50 Cal",
        "category": "Infantry Weapon",
        "subcategory": "Machine Gun",
        "manufacturer": "General Dynamics",
        "weight_lbs": 84,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0151",
        "nsn": "1005-01-476-1347",
        "nomenclature": "M240B/G Medium Machine Gun, 7.62mm",
        "common_name": "M240 Machine Gun",
        "category": "Infantry Weapon",
        "subcategory": "Machine Gun",
        "manufacturer": "FN Herstal",
        "weight_lbs": 27,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0152",
        "nsn": "1005-01-591-5826",
        "nomenclature": "M249 SAW, Light Machine Gun, 5.56mm",
        "common_name": "M249 SAW",
        "category": "Infantry Weapon",
        "subcategory": "Machine Gun",
        "manufacturer": "FN Herstal",
        "weight_lbs": 17,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0160",
        "nsn": "1005-01-395-0939",
        "nomenclature": "Mk19 Mod 3 Grenade Machine Gun, 40mm",
        "common_name": "Mk19 Grenade Launcher",
        "category": "Infantry Weapon",
        "subcategory": "Grenade Launcher",
        "manufacturer": "General Dynamics",
        "weight_lbs": 78,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0161",
        "nsn": "1010-01-360-7855",
        "nomenclature": "M203A2 Grenade Launcher, 40mm",
        "common_name": "M203 Under-barrel Launcher",
        "category": "Infantry Weapon",
        "subcategory": "Grenade Launcher",
        "manufacturer": "Colt",
        "weight_lbs": 3,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0162",
        "nsn": "1010-01-700-1234",
        "nomenclature": "M320 GLM, Grenade Launcher Module, 40mm",
        "common_name": "M320 Grenade Launcher",
        "category": "Infantry Weapon",
        "subcategory": "Grenade Launcher",
        "manufacturer": "Heckler & Koch",
        "weight_lbs": 4,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0200",
        "nsn": "1010-01-407-9800",
        "nomenclature": "M252A1 81mm Mortar",
        "common_name": "81mm Mortar",
        "category": "Infantry Weapon",
        "subcategory": "Mortar",
        "manufacturer": "Watervliet Arsenal",
        "weight_lbs": 91,
        "crew_size": 3,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0201",
        "nsn": "1015-01-484-8923",
        "nomenclature": "M224A1 60mm Mortar, Lightweight",
        "common_name": "60mm Mortar",
        "category": "Infantry Weapon",
        "subcategory": "Mortar",
        "manufacturer": "Watervliet Arsenal",
        "weight_lbs": 47,
        "crew_size": 3,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0300",
        "nsn": "1425-01-611-3869",
        "nomenclature": "FGM-148 Javelin, Anti-Tank Missile System",
        "common_name": "Javelin ATGM",
        "category": "Infantry Weapon",
        "subcategory": "Anti-Tank",
        "manufacturer": "Raytheon / Lockheed Martin",
        "weight_lbs": 49,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0301",
        "nsn": "1425-01-407-3271",
        "nomenclature": "BGM-71 TOW 2, Anti-Tank Missile System",
        "common_name": "TOW Missile System",
        "category": "Infantry Weapon",
        "subcategory": "Anti-Tank",
        "manufacturer": "Raytheon",
        "weight_lbs": 200,
        "crew_size": 4,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0310",
        "nsn": "1340-01-111-4512",
        "nomenclature": "M3E1 MAAWS, Multi-Role Anti-Armor Anti-Personnel Weapon System",
        "common_name": "Carl Gustaf 84mm Recoilless Rifle",
        "category": "Infantry Weapon",
        "subcategory": "Anti-Tank",
        "manufacturer": "Saab Bofors",
        "weight_lbs": 21,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0311",
        "nsn": "1340-01-520-7890",
        "nomenclature": "Mk153 SMAW, Shoulder-Launched Multi-Purpose Assault Weapon",
        "common_name": "SMAW Rocket Launcher",
        "category": "Infantry Weapon",
        "subcategory": "Assault",
        "manufacturer": "Nammo Talley",
        "weight_lbs": 17,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0312",
        "nsn": "1340-01-700-2345",
        "nomenclature": "M72A7 LAW, Light Anti-Tank Weapon",
        "common_name": "M72 LAW",
        "category": "Infantry Weapon",
        "subcategory": "Anti-Tank",
        "manufacturer": "Nammo",
        "weight_lbs": 6,
        "crew_size": 1,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0400",
        "nsn": "1430-01-700-3456",
        "nomenclature": "FIM-92 Stinger, Man-Portable Air-Defense System",
        "common_name": "Stinger MANPADS",
        "category": "Infantry Weapon",
        "subcategory": "Air Defense",
        "manufacturer": "Raytheon",
        "weight_lbs": 35,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "A0500",
        "nsn": "1005-01-700-4567",
        "nomenclature": "M18 Modular Handgun System, 9mm",
        "common_name": "M18 (Sig P320)",
        "category": "Infantry Weapon",
        "subcategory": "Pistol",
        "manufacturer": "Sig Sauer",
        "weight_lbs": 2,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    # -----------------------------------------------------------------------
    # COMMUNICATIONS EQUIPMENT (7 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "C0100",
        "nsn": "5820-01-522-7701",
        "nomenclature": "AN/PRC-117G(V)1(C), Multiband Manpack Radio",
        "common_name": "PRC-117G Manpack",
        "category": "Communications",
        "subcategory": "Manpack Radio",
        "manufacturer": "L3Harris",
        "weight_lbs": 12,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "C0101",
        "nsn": "5820-01-630-2345",
        "nomenclature": "AN/PRC-160(V)2, HF Manpack Radio",
        "common_name": "PRC-160 HF Radio",
        "category": "Communications",
        "subcategory": "Manpack Radio",
        "manufacturer": "L3Harris",
        "weight_lbs": 14,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "C0110",
        "nsn": "5820-01-451-8890",
        "nomenclature": "AN/PRC-152A, Multiband Handheld Radio",
        "common_name": "PRC-152 Handheld",
        "category": "Communications",
        "subcategory": "Handheld Radio",
        "manufacturer": "L3Harris",
        "weight_lbs": 3,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "C0120",
        "nsn": "5820-01-580-5678",
        "nomenclature": "AN/VRC-110(V), Vehicular Amplifier-Adapter",
        "common_name": "VRC-110 Vehicle Radio Kit",
        "category": "Communications",
        "subcategory": "Vehicle Radio",
        "manufacturer": "L3Harris",
        "weight_lbs": 45,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "C0200",
        "nsn": "5895-01-600-1234",
        "nomenclature": "AN/TRC-170(V)3, Digital Troposcatter Radio Terminal",
        "common_name": "TRC-170 Troposcatter",
        "category": "Communications",
        "subcategory": "Data Link",
        "manufacturer": "Raytheon",
        "weight_lbs": 2500,
        "crew_size": 6,
        "echelon_typical": "REGT",
    },
    {
        "tamcn": "C0210",
        "nsn": "5895-01-650-2345",
        "nomenclature": "AN/TSC-156 Phoenix Satellite Terminal",
        "common_name": "Phoenix SATCOM",
        "category": "Communications",
        "subcategory": "SATCOM",
        "manufacturer": "General Dynamics",
        "weight_lbs": 1800,
        "crew_size": 4,
        "echelon_typical": "REGT",
    },
    {
        "tamcn": "C0300",
        "nsn": "7010-01-700-5678",
        "nomenclature": "NOTM, Networking On-The-Move, Vehicle Kit",
        "common_name": "NOTM Vehicle Comms Suite",
        "category": "Communications",
        "subcategory": "Network",
        "manufacturer": "General Dynamics",
        "weight_lbs": 150,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    # -----------------------------------------------------------------------
    # OPTICS / NVG (5 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "A0600",
        "nsn": "5855-01-647-6498",
        "nomenclature": "AN/PSQ-42 ELRF, Enhanced Laser Range Finder",
        "common_name": "Laser Range Finder",
        "category": "Optics",
        "subcategory": "Targeting",
        "manufacturer": "DRS / Leonardo",
        "weight_lbs": 5,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0610",
        "nsn": "5855-01-596-4312",
        "nomenclature": "AN/PVS-31A BNVD, Binocular Night Vision Device",
        "common_name": "PVS-31 Night Vision Binoculars",
        "category": "Optics",
        "subcategory": "Night Vision",
        "manufacturer": "L3Harris",
        "weight_lbs": 1,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0611",
        "nsn": "5855-01-432-0524",
        "nomenclature": "AN/PVS-14 MNVD, Monocular Night Vision Device",
        "common_name": "PVS-14 NVG Monocular",
        "category": "Optics",
        "subcategory": "Night Vision",
        "manufacturer": "L3Harris / Elbit",
        "weight_lbs": 1,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0620",
        "nsn": "5855-01-501-4567",
        "nomenclature": "AN/PAS-13G(V)1 LWTS, Light Weapon Thermal Sight",
        "common_name": "Thermal Weapon Sight",
        "category": "Optics",
        "subcategory": "Thermal",
        "manufacturer": "DRS / Leonardo",
        "weight_lbs": 4,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "A0621",
        "nsn": "5855-01-700-6789",
        "nomenclature": "SQUAD-BIO, Squad Binocular, Day/Night, Fused",
        "common_name": "Squad Fused Binocular",
        "category": "Optics",
        "subcategory": "Fused",
        "manufacturer": "L3Harris",
        "weight_lbs": 3,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    # -----------------------------------------------------------------------
    # AVIATION — ROTARY WING (4 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "H0100",
        "nsn": "1520-01-234-5678",
        "nomenclature": "AH-1Z Viper, Attack Helicopter",
        "common_name": "Viper (Cobra)",
        "category": "Aviation",
        "subcategory": "Rotary Wing",
        "manufacturer": "Bell Textron",
        "weight_lbs": 18500,
        "crew_size": 2,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0101",
        "nsn": "1520-01-234-5679",
        "nomenclature": "UH-1Y Venom, Utility Helicopter",
        "common_name": "Venom (Huey)",
        "category": "Aviation",
        "subcategory": "Rotary Wing",
        "manufacturer": "Bell Textron",
        "weight_lbs": 18500,
        "crew_size": 4,
        "pax_capacity": 8,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0110",
        "nsn": "1520-01-345-6789",
        "nomenclature": "CH-53K King Stallion, Heavy Lift Helicopter",
        "common_name": "King Stallion",
        "category": "Aviation",
        "subcategory": "Rotary Wing",
        "manufacturer": "Sikorsky / Lockheed Martin",
        "weight_lbs": 88000,
        "crew_size": 5,
        "pax_capacity": 30,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0111",
        "nsn": "1520-01-345-6790",
        "nomenclature": "CH-53E Super Stallion, Heavy Lift Helicopter",
        "common_name": "Super Stallion",
        "category": "Aviation",
        "subcategory": "Rotary Wing",
        "manufacturer": "Sikorsky",
        "weight_lbs": 73500,
        "crew_size": 5,
        "pax_capacity": 37,
        "echelon_typical": "SQDN",
    },
    # -----------------------------------------------------------------------
    # AVIATION — FIXED WING (5 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "H0200",
        "nsn": "1510-01-456-7890",
        "nomenclature": "F-35B Lightning II, STOVL Strike Fighter",
        "common_name": "F-35B (STOVL)",
        "category": "Aviation",
        "subcategory": "Fixed Wing",
        "manufacturer": "Lockheed Martin",
        "weight_lbs": 60000,
        "crew_size": 1,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0201",
        "nsn": "1510-01-456-7891",
        "nomenclature": "F/A-18C/D Hornet, Strike Fighter",
        "common_name": "Hornet (Legacy)",
        "category": "Aviation",
        "subcategory": "Fixed Wing",
        "manufacturer": "Boeing",
        "weight_lbs": 51900,
        "crew_size": 2,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0210",
        "nsn": "1510-01-567-8901",
        "nomenclature": "MV-22B Osprey, Tiltrotor",
        "common_name": "Osprey",
        "category": "Aviation",
        "subcategory": "Tiltrotor",
        "manufacturer": "Bell / Boeing",
        "weight_lbs": 52600,
        "crew_size": 4,
        "pax_capacity": 24,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0220",
        "nsn": "1510-01-678-9012",
        "nomenclature": "KC-130J Super Hercules, Aerial Refueler/Transport",
        "common_name": "KC-130J Herc",
        "category": "Aviation",
        "subcategory": "Fixed Wing",
        "manufacturer": "Lockheed Martin",
        "weight_lbs": 164000,
        "crew_size": 6,
        "pax_capacity": 92,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0230",
        "nsn": "1510-01-700-7890",
        "nomenclature": "F/A-18E/F Super Hornet, Strike Fighter",
        "common_name": "Super Hornet",
        "category": "Aviation",
        "subcategory": "Fixed Wing",
        "manufacturer": "Boeing",
        "weight_lbs": 66000,
        "crew_size": 2,
        "echelon_typical": "SQDN",
        "notes": "Navy variant; included for joint ops tracking",
    },
    # -----------------------------------------------------------------------
    # AVIATION — UAS (4 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "H0300",
        "nsn": "1550-01-600-1234",
        "nomenclature": "RQ-21A Blackjack, Small Tactical UAS",
        "common_name": "Blackjack UAS",
        "category": "Aviation",
        "subcategory": "UAS",
        "manufacturer": "Insitu / Boeing",
        "weight_lbs": 135,
        "crew_size": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "H0301",
        "nsn": "1550-01-700-2345",
        "nomenclature": "MQ-9A Reaper, Medium-Altitude Long-Endurance UAS",
        "common_name": "Reaper UAS",
        "category": "Aviation",
        "subcategory": "UAS",
        "manufacturer": "General Atomics",
        "weight_lbs": 10500,
        "crew_size": 2,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "H0310",
        "nsn": "1550-01-700-3456",
        "nomenclature": "RQ-7B Shadow, Tactical UAS",
        "common_name": "Shadow UAS",
        "category": "Aviation",
        "subcategory": "UAS",
        "manufacturer": "AAI / Textron",
        "weight_lbs": 460,
        "crew_size": 4,
        "echelon_typical": "REGT",
    },
    {
        "tamcn": "H0320",
        "nsn": "1550-01-700-4567",
        "nomenclature": "RQ-20B Puma, Small UAS",
        "common_name": "Puma Hand-Launch UAS",
        "category": "Aviation",
        "subcategory": "UAS",
        "manufacturer": "AeroVironment",
        "weight_lbs": 14,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    # -----------------------------------------------------------------------
    # WATERCRAFT (5 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "W0100",
        "nsn": "1940-01-500-1234",
        "nomenclature": "LCAC, Landing Craft Air Cushion",
        "common_name": "LCAC Hovercraft",
        "category": "Watercraft",
        "subcategory": "Landing Craft",
        "manufacturer": "Textron",
        "weight_lbs": 182000,
        "crew_size": 5,
        "pax_capacity": 24,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "W0101",
        "nsn": "1940-01-700-5678",
        "nomenclature": "SSC, Ship-to-Shore Connector (LCAC 100)",
        "common_name": "SSC (Next-Gen LCAC)",
        "category": "Watercraft",
        "subcategory": "Landing Craft",
        "manufacturer": "Textron",
        "weight_lbs": 200000,
        "crew_size": 5,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "W0110",
        "nsn": "1940-01-600-2345",
        "nomenclature": "LCU 1610, Landing Craft Utility",
        "common_name": "LCU Landing Craft",
        "category": "Watercraft",
        "subcategory": "Landing Craft",
        "manufacturer": "Various Shipyards",
        "weight_lbs": 381000,
        "crew_size": 14,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "W0200",
        "nsn": "1940-01-650-3456",
        "nomenclature": "CRC, Combat Rubber Raiding Craft",
        "common_name": "Zodiac CRRC",
        "category": "Watercraft",
        "subcategory": "Inflatable",
        "manufacturer": "Zodiac",
        "weight_lbs": 265,
        "crew_size": 2,
        "pax_capacity": 10,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "W0210",
        "nsn": "1940-01-700-6789",
        "nomenclature": "SURC, Small Unit Riverine Craft",
        "common_name": "Riverine Patrol Boat",
        "category": "Watercraft",
        "subcategory": "Patrol",
        "manufacturer": "USMI",
        "weight_lbs": 16000,
        "crew_size": 4,
        "pax_capacity": 14,
        "echelon_typical": "CO",
    },
    # -----------------------------------------------------------------------
    # GENERATORS (7 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "G0100",
        "nsn": "6115-01-275-5061",
        "nomenclature": "MEP-831A, Generator Set, 3kW, 60Hz, Tactical",
        "common_name": "3kW Generator",
        "category": "Generator",
        "subcategory": "Tactical",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 200,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "G0101",
        "nsn": "6115-01-274-7392",
        "nomenclature": "MEP-832A, Generator Set, 5kW, 60Hz, Tactical",
        "common_name": "5kW Generator",
        "category": "Generator",
        "subcategory": "Tactical",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 350,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "G0102",
        "nsn": "6115-01-274-7393",
        "nomenclature": "MEP-803A, Generator Set, 10kW, 60Hz, Tactical",
        "common_name": "10kW Generator",
        "category": "Generator",
        "subcategory": "Tactical",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 560,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "G0103",
        "nsn": "6115-01-274-7394",
        "nomenclature": "MEP-804B, Generator Set, 15kW, 60Hz, Tactical",
        "common_name": "15kW Generator",
        "category": "Generator",
        "subcategory": "Tactical",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 750,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "G0104",
        "nsn": "6115-01-274-7395",
        "nomenclature": "MEP-805B, Generator Set, 30kW, 60Hz, Tactical",
        "common_name": "30kW Generator",
        "category": "Generator",
        "subcategory": "Tactical",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 1500,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "G0105",
        "nsn": "6115-01-274-7396",
        "nomenclature": "MEP-806B, Generator Set, 60kW, 60Hz, Tactical",
        "common_name": "60kW Generator",
        "category": "Generator",
        "subcategory": "Tactical",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 3500,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "G0106",
        "nsn": "6115-01-274-7397",
        "nomenclature": "MEP-PU-810B, Generator Set, 100kW, 60Hz, Precise Power",
        "common_name": "100kW Generator",
        "category": "Generator",
        "subcategory": "Precise Power",
        "manufacturer": "DRS / Dewey",
        "weight_lbs": 5200,
        "crew_size": 2,
        "echelon_typical": "REGT",
    },
    # -----------------------------------------------------------------------
    # CBRN EQUIPMENT (10 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "N0100",
        "nsn": "4240-01-361-1259",
        "nomenclature": "M50 JSGPM, Joint Service General Purpose Mask",
        "common_name": "M50 Gas Mask",
        "category": "CBRN",
        "subcategory": "Protective Mask",
        "manufacturer": "Avon Protection",
        "weight_lbs": 2,
        "crew_size": 1,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "N0101",
        "nsn": "4240-01-700-1234",
        "nomenclature": "M53A1 JSCESM, Joint Service Aircrew Mask",
        "common_name": "Aircrew CBRN Mask",
        "category": "CBRN",
        "subcategory": "Protective Mask",
        "manufacturer": "Avon Protection",
        "weight_lbs": 3,
        "crew_size": 1,
        "is_serialized": False,
        "echelon_typical": "SQDN",
    },
    {
        "tamcn": "N0110",
        "nsn": "4240-01-456-3210",
        "nomenclature": "JSLIST, Joint Service Lightweight Integrated Suit Technology",
        "common_name": "MOPP Suit",
        "category": "CBRN",
        "subcategory": "Protective Garment",
        "manufacturer": "Various",
        "weight_lbs": 6,
        "crew_size": 1,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "N0200",
        "nsn": "6665-01-456-7890",
        "nomenclature": "JCAD, Joint Chemical Agent Detector M4A1",
        "common_name": "JCAD Chemical Detector",
        "category": "CBRN",
        "subcategory": "Detection",
        "manufacturer": "Smiths Detection",
        "weight_lbs": 3,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "N0201",
        "nsn": "6665-01-500-1234",
        "nomenclature": "AN/PDR-77 RADIAC, Radiation Detection Set",
        "common_name": "RADIAC Meter",
        "category": "CBRN",
        "subcategory": "Detection",
        "manufacturer": "Canberra",
        "weight_lbs": 5,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "N0210",
        "nsn": "6665-01-550-2345",
        "nomenclature": "JBPDS, Joint Biological Point Detection System",
        "common_name": "Biological Agent Detector",
        "category": "CBRN",
        "subcategory": "Detection",
        "manufacturer": "Northrop Grumman",
        "weight_lbs": 85,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "N0300",
        "nsn": "4230-01-600-3456",
        "nomenclature": "M26 JCDS, Joint Contamination Decon System",
        "common_name": "Decon Shower System",
        "category": "CBRN",
        "subcategory": "Decontamination",
        "manufacturer": "DRS Defense",
        "weight_lbs": 7500,
        "crew_size": 8,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "N0301",
        "nsn": "4230-01-500-4567",
        "nomenclature": "M12A1 PDDA, Power Driven Decontamination Apparatus",
        "common_name": "Vehicle Decon System",
        "category": "CBRN",
        "subcategory": "Decontamination",
        "manufacturer": "Various",
        "weight_lbs": 1500,
        "crew_size": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "N0400",
        "nsn": "4240-01-700-5678",
        "nomenclature": "M8A1 BIDS, Biological Integrated Detection System",
        "common_name": "Bio Detection Van",
        "category": "CBRN",
        "subcategory": "Detection",
        "manufacturer": "Northrop Grumman",
        "weight_lbs": 12000,
        "crew_size": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "N0410",
        "nsn": "6665-01-700-6789",
        "nomenclature": "JSLSCAD, Joint Service Lightweight Standoff Chemical Agent Detector",
        "common_name": "Standoff Chemical Detector",
        "category": "CBRN",
        "subcategory": "Detection",
        "manufacturer": "General Dynamics",
        "weight_lbs": 160,
        "crew_size": 2,
        "echelon_typical": "REGT",
    },
    # -----------------------------------------------------------------------
    # EW EQUIPMENT (3 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "J0100",
        "nsn": "5895-01-700-7890",
        "nomenclature": "MRZR-LMADIS, Light Marine Air Defense Integrated System",
        "common_name": "LMADIS Counter-UAS",
        "category": "Electronic Warfare",
        "subcategory": "Counter-UAS",
        "manufacturer": "USMC / Various",
        "weight_lbs": 4000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "J0101",
        "nsn": "5895-01-700-8901",
        "nomenclature": "MADIS, Marine Air Defense Integrated System",
        "common_name": "MADIS (JLTV-mounted)",
        "category": "Electronic Warfare",
        "subcategory": "Air Defense / EW",
        "manufacturer": "Various",
        "weight_lbs": 18000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "J0200",
        "nsn": "5895-01-700-9012",
        "nomenclature": "AN/TLQ-11A, Electronic Attack Set",
        "common_name": "Crew-Served EW Jammer",
        "category": "Electronic Warfare",
        "subcategory": "Jamming",
        "manufacturer": "L3Harris",
        "weight_lbs": 250,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    # -----------------------------------------------------------------------
    # SHELTERS (6 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "S0100",
        "nsn": "5411-01-300-1234",
        "nomenclature": "DRASH XB Series, Deployable Rapid Assembly Shelter",
        "common_name": "DRASH Tent (Large)",
        "category": "Shelter",
        "subcategory": "Tent",
        "manufacturer": "DHS Systems",
        "weight_lbs": 2200,
        "crew_size": 4,
        "pax_capacity": 40,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "S0101",
        "nsn": "5411-01-300-2345",
        "nomenclature": "DRASH J Series, Joint Deployable Rapid Assembly Shelter",
        "common_name": "DRASH Tent (Medium)",
        "category": "Shelter",
        "subcategory": "Tent",
        "manufacturer": "DHS Systems",
        "weight_lbs": 1100,
        "crew_size": 4,
        "pax_capacity": 20,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "S0110",
        "nsn": "5410-01-400-3456",
        "nomenclature": "TEMPER Tent, Tent Expandable Modular Personnel",
        "common_name": "TEMPER Tent",
        "category": "Shelter",
        "subcategory": "Tent",
        "manufacturer": "Various",
        "weight_lbs": 800,
        "crew_size": 4,
        "pax_capacity": 16,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "S0200",
        "nsn": "5411-01-500-4567",
        "nomenclature": "S-788 ISO Shelter, Electronic Equipment Shelter",
        "common_name": "S-788 Rigid ISO Shelter",
        "category": "Shelter",
        "subcategory": "Rigid",
        "manufacturer": "AAR / Various",
        "weight_lbs": 4500,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "S0201",
        "nsn": "5411-01-500-5678",
        "nomenclature": "S-280 Shelter, Electrical Equipment",
        "common_name": "S-280 Rigid Shelter",
        "category": "Shelter",
        "subcategory": "Rigid",
        "manufacturer": "Various",
        "weight_lbs": 3000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "S0300",
        "nsn": "5411-01-600-6789",
        "nomenclature": "Base-X Tent, 305 Model",
        "common_name": "Base-X 305 Tent",
        "category": "Shelter",
        "subcategory": "Tent",
        "manufacturer": "HDT Global",
        "weight_lbs": 350,
        "crew_size": 2,
        "pax_capacity": 10,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    # -----------------------------------------------------------------------
    # WATER / FUEL SYSTEMS (7 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "P0100",
        "nsn": "4610-01-400-1234",
        "nomenclature": "TWPS, Tactical Water Purification System",
        "common_name": "TWPS Water Purifier",
        "category": "Water/Fuel System",
        "subcategory": "Water Purification",
        "manufacturer": "WRT / Zenon",
        "weight_lbs": 12000,
        "crew_size": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "P0101",
        "nsn": "4610-01-500-2345",
        "nomenclature": "LWP, Lightweight Water Purifier",
        "common_name": "Lightweight Water Purifier",
        "category": "Water/Fuel System",
        "subcategory": "Water Purification",
        "manufacturer": "SCEPTER / DRS",
        "weight_lbs": 800,
        "crew_size": 2,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "P0110",
        "nsn": "4930-01-400-3456",
        "nomenclature": "SIXCON Water Tank, 900-Gallon",
        "common_name": "SIXCON Water Tank",
        "category": "Water/Fuel System",
        "subcategory": "Storage",
        "manufacturer": "Various",
        "weight_lbs": 1200,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "P0200",
        "nsn": "4930-01-500-4567",
        "nomenclature": "SIXCON Fuel Tank, 900-Gallon",
        "common_name": "SIXCON Fuel Tank",
        "category": "Water/Fuel System",
        "subcategory": "Storage",
        "manufacturer": "Various",
        "weight_lbs": 1200,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "P0201",
        "nsn": "4930-01-600-5678",
        "nomenclature": "HIPPO, 2000-Gallon Water Distribution System",
        "common_name": "HIPPO Water Tanker",
        "category": "Water/Fuel System",
        "subcategory": "Distribution",
        "manufacturer": "Various",
        "weight_lbs": 18000,
        "crew_size": 2,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "P0210",
        "nsn": "4930-01-600-6789",
        "nomenclature": "FARE, Forward Area Refueling Equipment",
        "common_name": "FARE Fuel System",
        "category": "Water/Fuel System",
        "subcategory": "Fuel Distribution",
        "manufacturer": "Various",
        "weight_lbs": 3500,
        "crew_size": 4,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "P0220",
        "nsn": "4930-01-700-7890",
        "nomenclature": "AEF, Amphibious Assault Fuel System",
        "common_name": "Amphibious Fuel System",
        "category": "Water/Fuel System",
        "subcategory": "Fuel Distribution",
        "manufacturer": "Various",
        "weight_lbs": 25000,
        "crew_size": 6,
        "echelon_typical": "BN",
    },
    # -----------------------------------------------------------------------
    # ENGINEER EQUIPMENT (5 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "E1000",
        "nsn": "3805-01-400-1234",
        "nomenclature": "D7G Bulldozer, Medium, Armored",
        "common_name": "D7 Armored Bulldozer",
        "category": "Engineer Equipment",
        "subcategory": "Earthmoving",
        "manufacturer": "Caterpillar",
        "weight_lbs": 36000,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E1001",
        "nsn": "3805-01-500-2345",
        "nomenclature": "HMEE, High Mobility Engineer Excavator",
        "common_name": "JCB HMEE Backhoe",
        "category": "Engineer Equipment",
        "subcategory": "Excavation",
        "manufacturer": "JCB",
        "weight_lbs": 24000,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E1010",
        "nsn": "3895-01-600-3456",
        "nomenclature": "MK19 ROWPU, Reverse Osmosis Water Purification Unit (600 GPH)",
        "common_name": "600 GPH ROWPU",
        "category": "Engineer Equipment",
        "subcategory": "Water Purification",
        "manufacturer": "WRT",
        "weight_lbs": 8000,
        "crew_size": 3,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "E1020",
        "nsn": "3805-01-700-4567",
        "nomenclature": "SEE, Small Emplacement Excavator",
        "common_name": "Case 580 SEE",
        "category": "Engineer Equipment",
        "subcategory": "Excavation",
        "manufacturer": "Case / CNH",
        "weight_lbs": 16000,
        "crew_size": 1,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "E1030",
        "nsn": "3830-01-700-5678",
        "nomenclature": "MLC-70 Bridge, Medium Girder Bridge Set",
        "common_name": "Medium Girder Bridge",
        "category": "Engineer Equipment",
        "subcategory": "Bridging",
        "manufacturer": "WFEL",
        "weight_lbs": 45000,
        "crew_size": 20,
        "echelon_typical": "BN",
    },
    # -----------------------------------------------------------------------
    # FIELD SERVICES (5 items)
    # -----------------------------------------------------------------------
    {
        "tamcn": "F0100",
        "nsn": "7360-01-400-1234",
        "nomenclature": "MBU, Marine Burner Unit (Field Kitchen)",
        "common_name": "Field Kitchen Burner",
        "category": "Field Services",
        "subcategory": "Food Service",
        "manufacturer": "Babington Technology",
        "weight_lbs": 300,
        "crew_size": 2,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
    {
        "tamcn": "F0101",
        "nsn": "7360-01-500-2345",
        "nomenclature": "MFK, Modular Field Kitchen",
        "common_name": "Containerized Field Kitchen",
        "category": "Field Services",
        "subcategory": "Food Service",
        "manufacturer": "Karcher Futuretech",
        "weight_lbs": 8000,
        "crew_size": 6,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "F0200",
        "nsn": "3740-01-600-3456",
        "nomenclature": "TECS, Tactical Environmental Control System",
        "common_name": "TECS HVAC Unit",
        "category": "Field Services",
        "subcategory": "Climate Control",
        "manufacturer": "DRS / HDT",
        "weight_lbs": 350,
        "crew_size": 1,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "F0300",
        "nsn": "4510-01-700-4567",
        "nomenclature": "LFRS, Lightweight Fuel Recovery System",
        "common_name": "Fuel Spill Cleanup Kit",
        "category": "Field Services",
        "subcategory": "Environmental",
        "manufacturer": "Various",
        "weight_lbs": 500,
        "crew_size": 2,
        "is_serialized": False,
        "echelon_typical": "BN",
    },
    {
        "tamcn": "F0400",
        "nsn": "3750-01-700-5678",
        "nomenclature": "FDECU, Field Deployable Environmental Control Unit, 18K BTU",
        "common_name": "18K BTU ECU",
        "category": "Field Services",
        "subcategory": "Climate Control",
        "manufacturer": "HDT Global",
        "weight_lbs": 200,
        "crew_size": 1,
        "is_serialized": False,
        "echelon_typical": "CO",
    },
]


async def seed_equipment_catalog(db: AsyncSession) -> int:
    """Seed equipment catalog. Returns count of items inserted.

    Idempotent — checks TAMCN before inserting each item.
    """
    inserted = 0

    for item_data in _EQUIPMENT_CATALOG:
        tamcn = item_data.get("tamcn")
        if tamcn:
            result = await db.execute(
                select(EquipmentCatalogItem).where(EquipmentCatalogItem.tamcn == tamcn)
            )
            if result.scalar_one_or_none():
                continue

        record = EquipmentCatalogItem(**item_data)
        db.add(record)
        inserted += 1

    if inserted:
        await db.flush()

    return inserted
