import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import React from 'react';

// Mock API
vi.mock('../../../src/api/alerts', () => ({
  getAlerts: vi.fn(),
  acknowledgeAlert: vi.fn(),
  resolveAlert: vi.fn(),
  getAlertSummary: vi.fn(),
}));

vi.mock('../../../src/stores/dashboardStore', () => ({
  useDashboardStore: vi.fn((selector) => {
    const state = { selectedUnitId: null };
    return typeof selector === 'function' ? selector(state) : state;
  }),
}));

vi.mock('../../../src/hooks/useToast', () => ({
  useToast: () => ({
    success: vi.fn(),
    danger: vi.fn(),
    warning: vi.fn(),
    info: vi.fn(),
  }),
}));

vi.mock('../../../src/stores/toastStore', () => ({
  useToastStore: vi.fn((selector) => {
    const state = { addToast: vi.fn() };
    return typeof selector === 'function' ? selector(state) : state;
  }),
}));

vi.mock('../../../src/api/mockClient', () => ({
  isDemoMode: false,
  mockApi: {},
}));

vi.mock('../../../src/api/client', () => ({
  default: {
    get: vi.fn(),
    post: vi.fn(),
    interceptors: {
      request: { use: vi.fn() },
      response: { use: vi.fn() },
    },
  },
}));

vi.mock('../../../src/api/demoUsers', () => ({
  DEMO_USERS_LIST: [],
}));

vi.mock('../../../src/api/mockData', () => ({
  DEMO_SUPPLY_RECORDS: [],
  DEMO_INDIVIDUAL_EQUIPMENT: [],
  DEMO_WORK_ORDERS: [],
  DEMO_UNITS: [],
  DEMO_ALERTS: [],
  DEMO_MOVEMENTS: [],
  DEMO_REPORTS: [],
  DEMO_PERSONNEL: [],
}));

// Mock sub-components that might be hard to render
vi.mock('../../../src/components/ui/Card', () => ({
  default: ({ title, children }: { title: string; children: React.ReactNode }) =>
    React.createElement('div', { 'data-testid': 'card', 'data-title': title }, children),
}));

vi.mock('../../../src/components/ui/StatusDot', () => ({
  default: ({ status, size }: { status: string; size: number }) =>
    React.createElement('span', { 'data-testid': 'status-dot', 'data-status': status }),
}));

import AlertsTab from '../../../src/pages/alerts/AlertsTab';
import * as alertsApi from '../../../src/api/alerts';

const MOCK_ALERTS = [
  {
    id: '1',
    type: 'LOW_DOS',
    severity: 'CRITICAL',
    unitId: 'u1',
    unitName: '1/1 BN',
    title: 'CL III Below 2 DOS',
    message: 'MOGAS critically low',
    acknowledged: false,
    resolved: false,
    escalated: false,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    type: 'LOW_READINESS',
    severity: 'WARNING',
    unitId: 'u2',
    unitName: 'Alpha Co',
    title: 'Equipment Readiness Low',
    message: 'Readiness at 65%',
    acknowledged: true,
    acknowledgedBy: 'SSgt Smith',
    acknowledgedAt: new Date().toISOString(),
    resolved: false,
    escalated: false,
    autoGenerated: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '3',
    type: 'SYSTEM',
    severity: 'INFO',
    unitId: 'u3',
    unitName: 'HQ Co',
    title: 'System Check Complete',
    message: 'All systems nominal',
    acknowledged: false,
    resolved: true,
    resolvedBy: 'Admin',
    resolvedAt: new Date().toISOString(),
    escalated: false,
    autoGenerated: true,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

const MOCK_SUMMARY = {
  total_active: 1,
  by_severity: { CRITICAL: 1, WARNING: 0, INFO: 0 },
  by_type: {},
};

function renderAlertsTab() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
    },
  });

  return render(
    <QueryClientProvider client={queryClient}>
      <AlertsTab />
    </QueryClientProvider>,
  );
}

describe('AlertsTab', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(alertsApi.getAlerts).mockResolvedValue(MOCK_ALERTS as any);
    vi.mocked(alertsApi.getAlertSummary).mockResolvedValue(MOCK_SUMMARY as any);
  });

  it('renders summary cards', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('TOTAL ACTIVE')).toBeInTheDocument();
      // CRITICAL/WARNING/INFO appear both as summary cards and as filter options
      expect(screen.getAllByText('CRITICAL').length).toBeGreaterThanOrEqual(1);
      expect(screen.getAllByText('WARNING').length).toBeGreaterThanOrEqual(1);
      expect(screen.getAllByText('INFO').length).toBeGreaterThanOrEqual(1);
    });
  });

  it('renders severity filter dropdown', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByDisplayValue('ALL SEVERITIES')).toBeInTheDocument();
    });
  });

  it('renders show acknowledged checkbox', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('SHOW ACKNOWLEDGED')).toBeInTheDocument();
    });
  });

  it('renders show resolved checkbox', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('SHOW RESOLVED')).toBeInTheDocument();
    });
  });

  it('shows unacknowledged unresolved alerts by default', async () => {
    renderAlertsTab();

    await waitFor(() => {
      // Alert 1 is not acknowledged and not resolved -> shown
      expect(screen.getByText('CL III Below 2 DOS')).toBeInTheDocument();
    });

    // Alert 2 is acknowledged -> hidden by default
    expect(screen.queryByText('Equipment Readiness Low')).not.toBeInTheDocument();
    // Alert 3 is resolved -> hidden by default
    expect(screen.queryByText('System Check Complete')).not.toBeInTheDocument();
  });

  it('shows acknowledged alerts when checkbox is checked', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('CL III Below 2 DOS')).toBeInTheDocument();
    });

    const checkbox = screen.getByText('SHOW ACKNOWLEDGED').parentElement!.querySelector('input')!;
    fireEvent.click(checkbox);

    await waitFor(() => {
      expect(screen.getByText('Equipment Readiness Low')).toBeInTheDocument();
    });
  });

  it('shows resolved alerts when checkbox is checked', async () => {
    renderAlertsTab();

    // Wait for data to load
    await waitFor(() => {
      expect(screen.getByText('CL III Below 2 DOS')).toBeInTheDocument();
    });

    // Alert 3 (resolved) should be hidden initially
    expect(screen.queryByText('System Check Complete')).not.toBeInTheDocument();

    // Check SHOW RESOLVED by clicking the label text
    const allCheckboxes = screen.getAllByRole('checkbox');
    // Second checkbox is SHOW RESOLVED (first is SHOW ACKNOWLEDGED)
    fireEvent.click(allCheckboxes[1]);

    // Now the resolved alert (alert 3) should appear in the filtered list
    await waitFor(() => {
      // The card title should reflect the updated count
      const card = screen.getByTestId('card');
      expect(card.getAttribute('data-title')).toBe('ALERTS (2)');
    });
  });

  it('filters by severity when dropdown changes', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('CL III Below 2 DOS')).toBeInTheDocument();
    });

    // Change filter to INFO (no unack/unresolved INFO alerts)
    const select = screen.getByDisplayValue('ALL SEVERITIES');
    fireEvent.change(select, { target: { value: 'INFO' } });

    // Alert 1 is CRITICAL -> hidden
    await waitFor(() => {
      expect(screen.queryByText('CL III Below 2 DOS')).not.toBeInTheDocument();
    });
  });

  it('renders ACK button for unacknowledged alert', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('ACK')).toBeInTheDocument();
    });
  });

  it('renders RESOLVE button for unresolved alert', async () => {
    renderAlertsTab();

    await waitFor(() => {
      expect(screen.getByText('RESOLVE')).toBeInTheDocument();
    });
  });

  it('displays alert count in card title', async () => {
    renderAlertsTab();

    await waitFor(() => {
      const card = screen.getByTestId('card');
      expect(card.getAttribute('data-title')).toMatch(/ALERTS \(\d+\)/);
    });
  });
});
